// Generated by gencpp from file asr_record/sr_order.msg
// DO NOT EDIT!


#ifndef ASR_RECORD_MESSAGE_SR_ORDER_H
#define ASR_RECORD_MESSAGE_SR_ORDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asr_record
{
template <class ContainerAllocator>
struct sr_order_
{
  typedef sr_order_<ContainerAllocator> Type;

  sr_order_()
    : order(0)  {
    }
  sr_order_(const ContainerAllocator& _alloc)
    : order(0)  {
  (void)_alloc;
    }



   typedef int16_t _order_type;
  _order_type order;




  typedef boost::shared_ptr< ::asr_record::sr_order_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asr_record::sr_order_<ContainerAllocator> const> ConstPtr;

}; // struct sr_order_

typedef ::asr_record::sr_order_<std::allocator<void> > sr_order;

typedef boost::shared_ptr< ::asr_record::sr_order > sr_orderPtr;
typedef boost::shared_ptr< ::asr_record::sr_order const> sr_orderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asr_record::sr_order_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asr_record::sr_order_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asr_record

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'asr_record': ['/home/trobot/robot_ws/src/asr_record/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asr_record::sr_order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asr_record::sr_order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asr_record::sr_order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asr_record::sr_order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asr_record::sr_order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asr_record::sr_order_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asr_record::sr_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2966e63ad91c66f88bbe7ef4becb02eb";
  }

  static const char* value(const ::asr_record::sr_order_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2966e63ad91c66f8ULL;
  static const uint64_t static_value2 = 0x8bbe7ef4becb02ebULL;
};

template<class ContainerAllocator>
struct DataType< ::asr_record::sr_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asr_record/sr_order";
  }

  static const char* value(const ::asr_record::sr_order_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asr_record::sr_order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 order\n\
";
  }

  static const char* value(const ::asr_record::sr_order_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asr_record::sr_order_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sr_order_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asr_record::sr_order_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asr_record::sr_order_<ContainerAllocator>& v)
  {
    s << indent << "order: ";
    Printer<int16_t>::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASR_RECORD_MESSAGE_SR_ORDER_H
